RepeatRoot -> SeqMain

SeqMain -> AlwaysSucc1

AlwaysSucc1 -> SeqPathfind

SeqPathfind -> OnGround1
SeqPathfind -> SetNextPoint

SeqMain -> SelFollow

SelFollow -> InvertAttack
InvertAttack -> SeqAttack

SeqAttack -> OnGround2
SeqAttack -> RaycastToTarget
SeqAttack -> TargetInRange
SeqAttack -> AttackTarget

SelFollow -> InvertWalkHorizontal
SelFollow -> SeqJump

SeqJump -> OnGround3
SeqJump -> Jump

InvertWalkHorizontal -> WalkHorizontal
